config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :sessions => "users/sessions",:registrations => "users/registrations" }, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'} do
    get '/users', :to => 'users/registrations#index'
    get '/login', :to => 'users/sessions#new'
    get '/signup', :to => 'users/registrations#new'    
  end
  
  resources :installs,:intro,:histories,:contacts,:faq_categories, :faqs, :about, :gallery_categories, :galleries, :notices, :portfolios, :user_photos 
    
  resources :blogs do
    resources :blog_comments
  end
  
  resources :questions do
    get 'password',:on=>:collection
    post 'password',:on=>:collection    
    resources :question_comments
  end
  
  resources :guest_books do
    get 'password',:on=>:collection
    post 'password',:on=>:collection    
    resources :guest_book_comments do
      get 'password',:on=>:collection
      post 'password',:on=>:collection      
    end
  end
  
  get 'home/popup'=>'home#popup'
  
  get 'tags/:tag', to: 'blogs#index', as: :tag  
  
  get 'blogs/:blog_id/blog_comments/:id/password',:to=>'blog_comments#password'
  post 'blogs/:blog_id/blog_comments/:id/password',:to=>'blog_comments#password'
  
  
  get 'guest_books/:guest_book_id/:id/password',:to=>'guest_books#password'
  post 'guest_books/:guest_book_id/:id/password',:to=>'guest_books#password'    
  
  get 'guest_books/:guest_book_id/guest_book_comments/:id/password',:to=>'guest_book_comments#password'
  post 'guest_books/:guest_book_id/guest_book_comments/:id/password',:to=>'guest_book_comments#password'  
  
  # admin 
  get '/admin', :to=>'admin/home#index'
  
  namespace :admin do
    resources :resources,:users
    resources :intro,:gallery_categories, :galleries, :faq_categories,:faqs, :notices, :site, :intro, :contacts, :notices, :histories, :portfolios
    resources :questions do
      resources :question_comments
    end
    
    resources :blogs do
      resources :blog_comments
    end
    
    resources :questions do
      get 'password',:on=>:collection
      post 'password',:on=>:collection    
      resources :question_comments
    end
  
    resources :guest_books do
      resources :guest_book_comments do
        get 'password',:on=>:collection
        post 'password',:on=>:collection      
      end
    end    
  end
end

app/models/gallery.rb
# encoding: utf-8

require 'carrierwave/orm/activerecord'

class Gallery < ActiveRecord::Base
  validates_presence_of :title, :photo
  validates_length_of :title, :minimum => 4, :maximum => 60, :allow_blank => true  
  belongs_to :user, :autosave => true  
  belongs_to :gallery_category, :autosave => true, :counter_cache => true
  translates :title, :location, :content  
  mount_uploader :photo, GalleryUploader
end

app/controllers/admin/galleries_controller.rb
# encoding: utf-8

class Admin::GalleriesController < Admin::AdminController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]
  
  def initialize(*params)
    super(*params)   
    @controller_name=t('activerecord.models.gallery')
    @script="galleries"
    @meta_description='예쁘고 귀여운 수정이의 사진첩입니다.'
    
    get_menu('galleries')
  end
  
  # GET /galleries
  # GET /galleries.json
  def index
    if params[:gallery_category_id]
      @admin_galleries = Gallery.where(:gallery_category_id=> params[:gallery_category_id]).order('id desc').page(params[:page]).per(15)
    else 
      @admin_galleries = Gallery.order('id desc').page(params[:page]).per(15)
    end
    
    @script='galleries'    
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @admin_galleries }
    end
  end
  
  # GET /galleries/1
  # GET /galleries/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @admin_gallery }
    end
  end
  
  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @admin_gallery = Gallery.new
    @admin_gallery_categories=GalleryCategory.all
    @admin_gallery_category_id=params[:gallery_category_id]
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @admin_gallery }
    end
  end
  
  # GET /galleries/1/edit
  def edit
    @admin_gallery_categories=GalleryCategory.all
    @admin_gallery_category_id=@admin_gallery.gallery_category.id    
  end
  
  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.user_id=current_user.id    
    
    respond_to do |format|
      if @gallery.save
        format.html { redirect_to admin_gallery_url(@gallery), :notice=> @controller_name +t(:message_success_create)}
        format.json { render :json => @gallery, :status => :created, :location => @gallery }
      else
        format.html { render :action => "new" }
        format.json { render :json => @gallery.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    respond_to do |format|
      if @admin_gallery.update_attributes(gallery_params)
        format.html { redirect_to admin_galleries_url, :notice=> @controller_name +t(:message_success_update)}
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @admin_gallery.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @admin_gallery.destroy
    
    respond_to do |format|
      format.html { redirect_to admin_galleries_url }
      format.json { head :ok }
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_gallery
    @admin_gallery = Gallery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gallery_params
    params.require(:gallery).permit(:id,:gallery_category_id,:title,:photo,:content)
  end  
end

app/controllers/galleries_controller.rb
# encoding: utf-8
class GalleriesController < BoardController
  impressionist :actions=>[:show]
  before_action :authenticate_user!, :except => [:index,:show]
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]
  def initialize(*params)
    super(*params)
    @controller_name=t('activerecord.models.gallery')
    @script="galleries"
    @title=t('activerecord.models.gallery')
    @meta_description=t(:meta_description_gallery)
    @page_itemtype="http://schema.org/ImageGallery"
  end

  # GET /galleries
  # GET /galleries.json
  def index
      @gallery_categories=GalleryCategory.all

      if(params[:gallery_category_id])
        @gallery_category_id=params[:gallery_category_id].to_i
      else
        if @gallery_categories[0]
          @gallery_category_id=@gallery_categories[0].id.to_i
        else
          @gallery_category_id=nil
        end
      end

      @galleries = Gallery.where(:gallery_category_id=>@gallery_category_id).order('id desc').page(params[:page]).per(10)

    if(params[:id])
      @gallery = Gallery.find(params[:id])
    else
      @gallery=@galleries[0]
    end

    if @gallery
      @title=@gallery.title
      @meta_description=@gallery.content
    end

    @script='galleries'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    if @menu_setting.use_category
      @gallery_categories=GalleryCategory.all
      @gallery_category_id=@gallery.gallery_category_id
      @galleries = Gallery.where(:gallery_category_id=>@gallery_category_id).order(@menu_setting.order).page(params[:page]).per(@menu_setting.per)
    else
      @galleries = Gallery.order(@menu_setting.order).page(params[:page]).per(@menu_setting.per)
    end

    if @gallery
      @title=@gallery.title
      @meta_description=@gallery.content
    end

    @script='galleries'

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new
    @gallery_categories=GalleryCategory.all
    if(params[:gallery_category_id])
      @gallery_category_id=params[:gallery_category_id]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery_categories=GalleryCategory.all
    @gallery_category_id=@gallery.gallery_category.id
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.user_id=current_user.id

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to gallery_url(@gallery), :notice=> @controller_name +t(:message_success_create)}
        format.json { render :json => @gallery, :status => :created, :location => @gallery }
      else
        format.html { render :action => "new" }
        format.json { render :json => @gallery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update_attributes(gallery_params)
        format.html { redirect_to gallery_url(@gallery), :notice=> @controller_name +t(:message_success_update)}
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @gallery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url(:gallery_category_id=>@gallery.gallery_category_id) }
      format.json { head :ok }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gallery_params
    params.require(:gallery).permit(:id,:user_id,:gallery_category_id,:title,:photo,:photo_cache,:content)
  end
end

app/views/admin/galleries/_form.html.erb
<%= form_for [:admin, @admin_gallery],:html => {:multipart => true,:class=>'form-horizontal'} do |f| %>
  <% if @admin_gallery.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@admin_gallery.errors.count, "error") %> prohibited this notice from being saved:</h2>
    <ul>
      <% @admin_gallery.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :gallery_category_id,:class=>'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.select :gallery_category_id, options_from_collection_for_select(GalleryCategory.where(:enable=>true), 'id', 'title',@gallery_category_id),:class=>'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title,:class=>'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title,:class=>'form-control',:required=>'required' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :photo,:class=>'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <% if @admin_gallery.photo? %>
      <%= image_tag(@admin_gallery.photo.small_thumb) %>
      <% end %>
      <%= f.file_field :photo %>
      <%= f.hidden_field :photo_cache %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content,:class=>'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :content,:class=>'form-control',:required=>'required' %>
    </div>
  </div>
  <div class="form-group actions">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class=>"btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/galleries/edit.html.erb
<section id="admin_resource_edit">
  <%= render 'form' %>
  <%= link_to t(:link_show), admin_gallery_path(@admin_gallery) %> |
  <%= link_to t(:link_list), admin_galleries_path %>
</section>

app/views/admin/galleries/index.html.erb
<section id="sl_notice_index" class="table-responsive"> 
  <table width="100%" cellpadding="0" cellspacing="0" class="table table-striped table-hover">
		<colgroup>
			<col width="100px" />
			<col />
			<col width="70px" />
			<col width="130px" />
    <% if can?(:update, Gallery) || can?(:delete, Gallery) %>
    <col <%=raw manage_width(Gallery) %> />
    <% end %>			
		</colgroup>
		<thead>
			<tr>
				<th><p class="sl_name"><%=t(:label_photo) %></p></th>
				<th><p class="sl_title"><%=t(:label_title) %></p></th>
				<th class="sl_right"><p class="sl_count">조회</p></th>
				<th class="sl_right"><p class="sl_registered_date">등록일</p></th>
   <th class="sl_right"><p class="sl_manage"><%=t(:label_manage) %></p></th>				
			</tr>
		</thead>
		<tbody>
			<tr class="none">
				<td><p class="sl_name"></p></td>
				<td><p><a class="sl_show_link" href="show.php"></a></p></td>
				<td class="sl_right"><p class="sl_count"></p></td>
				<td class="sl_right"><p class="sl_registered_date"></p></td>
			</tr>
			<% unless @admin_galleries.empty? %>
			<% @admin_galleries.each do |admin_gallery| %>
			<tr>
				<td><%=image_tag admin_gallery.photo.small_thumb %></td>
				<td><p><%= link_to admin_gallery.title, admin_gallery_path(admin_gallery)  %></p></td>
				<td class="sl_right"><p class="sl_count"></p></td>
				<td class="sl_right"><p class="sl_registered_date"><%=admin_gallery.created_at.to_date %></p></td>
      <% if can?(:update, admin_gallery) || can?(:delete, admin_gallery) %>
      <td>
        <% if can? :update, admin_gallery %>
        <%= link_to edit_admin_gallery_path(admin_gallery),:class=>"btn btn-default btn-sm" do %>
        <i class="glyphicon glyphicon-pencil"></i> <%=t(:link_edit) %>
        <% end %>
        <% end %>
        <% if can? :delete, admin_gallery %>
        <%= link_to admin_gallery_path(admin_gallery), :method => :delete, :data => { :confirm => t(:delete_confirm) },:class=>"btn btn-sm btn-danger pull-right" do %>
        <i class="glyphicon glyphicon-trash"></i> <%=t(:link_delete) %>
        <% end %>
        <% end %>
      </td>
      <% end %>
			</tr>
			<% end %>			
			<% else %>
			<tr>
        <td colspan="5"><p><%=t(:no_data) %></p></td>
			</tr>
			<% end %>
		</table>
		<div id="sl_bottom_menu">
		<% if can? :create,Gallery %>
	<%= link_to '글쓰기', new_admin_gallery_path %>
	<% end %>
				<%= paginate @admin_galleries %>
	</div>
</section>

app/views/admin/galleries/new.html.erb
<section id="admin_resource_new">
  <%= render 'form' %>
  <%= link_to t(:link_list), admin_galleries_path %>
</section>

app/views/admin/galleries/show.html.erb
<section id="admin_gallery_show">
	<p id="notice"><%= notice %></p>	
	<div class="slboard_content">
		<div class="sl_content_header">
			<h3><%= @admin_gallery.title %></h3>
			<p>&nbsp;&nbsp;&nbsp; 작성일 : <%= @admin_gallery.created_at %></p>
		</div>
		<div class="sl_content_main">
			<div class="sl_content_text">  <%= simple_format(@admin_gallery.content) %></div>
		</div>
	</div>
	<div id="sl_bottom_menu">
  <% if can? :manage, @admin_gallery %>
		<%= link_to '글쓰기', new_admin_gallery_path %>
		<%= link_to '글수정', edit_admin_gallery_path(@admin_gallery) %>
		<% end %>
		<%= link_to '목록으로',admin_galleries_path %>
	</div>
</section>