config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :sessions => "users/sessions",:registrations => "users/registrations" }, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'} do
    get '/users', :to => 'users/registrations#index'
    get '/login', :to => 'users/sessions#new'
    get '/signup', :to => 'users/registrations#new'    
  end
  
  resources :installs,:intro,:histories,:contacts,:faq_categories, :faqs, :about, :gallery_categories, :galleries, :notices, :portfolios, :user_photos 
    
  resources :blogs do
    resources :blog_comments
  end
  
  resources :questions do
    get 'password',:on=>:collection
    post 'password',:on=>:collection    
    resources :question_comments
  end
  
  resources :guest_books do
    get 'password',:on=>:collection
    post 'password',:on=>:collection    
    resources :guest_book_comments do
      get 'password',:on=>:collection
      post 'password',:on=>:collection      
    end
  end
  
  get 'home/popup'=>'home#popup'
  
  get 'tags/:tag', to: 'blogs#index', as: :tag  
  
  get 'blogs/:blog_id/blog_comments/:id/password',:to=>'blog_comments#password'
  post 'blogs/:blog_id/blog_comments/:id/password',:to=>'blog_comments#password'
  
  
  get 'guest_books/:guest_book_id/:id/password',:to=>'guest_books#password'
  post 'guest_books/:guest_book_id/:id/password',:to=>'guest_books#password'    
  
  get 'guest_books/:guest_book_id/guest_book_comments/:id/password',:to=>'guest_book_comments#password'
  post 'guest_books/:guest_book_id/guest_book_comments/:id/password',:to=>'guest_book_comments#password'  
  
  # admin 
  get '/admin', :to=>'admin/home#index'
  
  namespace :admin do
    resources :resources,:users
    resources :intro,:gallery_categories, :galleries, :faq_categories,:faqs, :notices, :site, :intro, :contacts, :notices, :histories, :portfolios
    resources :questions do
      resources :question_comments
    end
    
    resources :blogs do
      resources :blog_comments
    end
    
    resources :questions do
      get 'password',:on=>:collection
      post 'password',:on=>:collection    
      resources :question_comments
    end
  
    resources :guest_books do
      resources :guest_book_comments do
        get 'password',:on=>:collection
        post 'password',:on=>:collection      
      end
    end    
  end
end

app/models/faq.rb
# encoding: utf-8

class Faq < ActiveRecord::Base
  validates_presence_of :title
  belongs_to :faq_category, :autosave=>true  
  has_one :faq_content, :foreign_key => :id, :dependent=>:destroy
  accepts_nested_attributes_for :faq_content, :allow_destroy => true  
end

app/controllers/admin/faqs_controller.rb
# encoding: utf-8

class Admin::FaqsController < Admin::AdminController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]
  
  def initialize(*params)
    super(*params)   
    @controller_name=t('activerecord.models.faq')
    @script="board/index"
    @meta_description='예쁘고 귀여운 수정이의  FAQ입니다.'
    
    get_menu('faqs')
  end
  
  # GET /faqs
  # GET /faqs.json
  def index
    @admin_faq_categories = FaqCategory.all
    
    if(params[:faq_category_id])
      @categoryId=params[:faq_category_id].to_i
    else
      if @admin_faq_categories[0]
        @categoryId=@admin_faq_categories[0].id.to_i
      else
        @categoryId=nil        
      end
    end
    
    @admin_faqs = Faq.where(:faq_category_id=>@categoryId).order(@menu_setting.order).page(params[:page]).per(@menu_setting.per)
    
    if(params[:id])
      @admin_faq = Faq.find(params[:id])
    end
    
    @script='faqs'
    
    admin=false
    if(current_user)
      if(current_user.admin)
        admin=true
      end
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {:faqs=>@admin_faqs,:admin=>admin} }
    end
  end
  
  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @admin_faqContent=FaqContent.find(params[:id])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_faqContent }
    end
  end
  
  # GET /faqs/new
  # GET /faqs/new.json
  def new
    @admin_faq = Faq.new
    @admin_faq.build_faq_content
    @admin_faq_categories = FaqCategory.all
    @admin_faq_category_id=params[:faq_category_id]
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_faq }
    end
  end
  
  # GET /faqs/1/edit
  def edit
    @admin_faq_categories = FaqCategory.all
    @admin_faq_category_id=@admin_faq.faq_category.id
  end
  
  # POST /faqs
  # POST /faqs.json
  def create
    @admin_faq = Faq.new(faq_params)
    
    respond_to do |format|
      if @admin_faq.save
        format.html { redirect_to admin_faqs_url, :notice=> @controller_name +t(:message_success_create)}
        format.json { render json: @admin_faq, status: :created, location: @admin_faq }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_faq.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /faqs/1
  # PUT /faqs/1.json
  def update
    @admin_faq = Faq.find(params[:id])
    
    respond_to do |format|
      if @admin_faq.update_attributes(faq_params)
        format.html { redirect_to admin_faqs_url, :notice=> @controller_name +t(:message_success_update)}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_faq.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @admin_faq.destroy
    
    respond_to do |format|
      format.html { redirect_to admin_faqs_url}
      format.json { head :ok }
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_faq
    @admin_faq = Faq.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def faq_params
    params.require(:faq).permit(:id,:faq_category_id,:title)
  end  
end

app/controllers/faqs_controller.rb
# encoding: utf-8

class FaqsController < BoardController
  before_action :authenticate_user!, :except => [:index,:show]  
  before_action :set_faq, only: [:show, :edit, :update, :destroy]  
  
  def initialize(*params)
    super(*params)   
    @controller_name=t('activerecord.models.faq')
    @script="faqs"
    @title=t('activerecord.models.faq')+t(:title_separator)+t(:application_name)    
    @meta_description=t(:meta_description_faq)
    @page_itemtype="http://schema.org/QAPage" 
  end
  
  # GET /faqs
  # GET /faqs.json
  def index
    @faq_categories = FaqCategory.all
    
    if(params[:faq_category_id])
      @categoryId=params[:faq_category_id].to_i
    else
      if @faq_categories[0]
        @categoryId=@faq_categories[0].id.to_i
      else
        @categoryId=nil        
      end
    end
    
    @faqs = Faq.where(:faq_category_id=>@categoryId).order('id desc').page(params[:page]).per(10)
    
    if(params[:id])
      @faq = Faq.find(params[:id])
    end
    
    @script='faqs'
    
    admin=false
    if(current_user)
      if(current_user.admin)
        admin=true
      end
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {:faqs=>@faqs,:admin=>admin} }
    end
  end
  
  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faqContent=FaqContent.find(params[:id])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faqContent }
    end
  end
  
  # GET /faqs/new
  # GET /faqs/new.json
  def new
    @faq = Faq.new
    @faq.build_faq_content
    @faq_categories = FaqCategory.all
    @faq_category_id=params[:faq_category_id]
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faq }
    end
  end
  
  # GET /faqs/1/edit
  def edit
    @faq_categories = FaqCategory.all
    @faq_category_id=@faq.faq_category.id
  end
  
  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)
    
    respond_to do |format|
      if @faq.save
        format.html { redirect_to faqs_url(:faq_category_id=>@faq.faq_category.id), :notice=> @controller_name +t(:message_success_create)}
        format.json { render json: @faq, status: :created, location: @faq }
      else
        format.html { render action: "new" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /faqs/1
  # PUT /faqs/1.json
  def update
    @faq = Faq.find(params[:id])
    
    respond_to do |format|
      if @faq.update_attributes(faq_params)
        format.html { redirect_to faqs_url(:faq_category_id=>@faq.faq_category.id), :notice=> @controller_name +t(:message_success_update)}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    
    respond_to do |format|
      format.html { redirect_to faqs_url(:faq_category_id=>@faq.faq_category.id) }
      format.json { head :ok }
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_faq
    @faq = Faq.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def faq_params
    params.require(:faq).permit(:id,:faq_category_id,:title)
  end  
end

app/views/faqs/_form.html.erb
<%=form_for @faq,:html=>{:class=>'slboard_form'} do |f| %>
  <% if @faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error") %> prohibited this faq from being saved:</h2>
      <ul>
      <% @faq.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>    
  <% end %>
  <div class="form-group">
    <%= f.label :faq_category_id %><br />
    <%= f.select :faq_category_id, options_from_collection_for_select(@faq_categories, 'id', 'title',@faq_category_id), :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, :class=>'form-control',:required=>'required' %>
  </div>
	<%= f.fields_for :faq_content do |c| %>
  <div class="form-group">
    <%= c.label :content  %><br />
    <%= c.text_area :content, :class=>'form-control',:required=>'required' %>
  </div>
	<% end %>  
  <div class="form-group actions">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/faqs/_index.html.erb
<article id="sl_main_faq" class="sl_main_list">
	<h3><%=t('activerecord.models.faq') %></h3>
	<ul>
		<% unless @faqs.empty? %>
		<% @faqs.each do |faq| %>
		<li>
			<%= link_to faq.title.truncate(16), faqs_path(:id=>faq)  %>
			<span class="sl_registered_date"><%=faq.created_at.to_date %></span>
		</li>
		<% end %>	
		<% else %>
		<li><%=t(:no_data) %></li>
		<% end %>
	</ul>
	<%=link_to t(:link_more),faqs_path,:class=>'more' %>
</article>

app/views/faqs/edit.html.erb
<section id="sl_faq_edit">
	<%= render 'form' %>
	<%= link_to t(:link_list), faqs_path %>
</section>

app/views/faqs/index.html.erb
<% breadcrumb :faqs %>
<% if notice %>
<%= render :partial => 'layouts/notice',:locals=>{:notice=>notice} %>
<% end %>
<section id="sl_faq_index">	
		<ol class="nav nav-tabs">
			<% unless @faq_categories.empty? %>
			<% @faq_categories.each do |faq_category| %>			
			<li <% if(@categoryId==faq_category.id) %>class="active"<% end %>>
				<%= link_to truncate(faq_category.title,:length => 20),faqs_path(:faq_category_id=>faq_category.id),{:class=>'title'} %>
				<% if(@categoryId==faq_category.id) %>				
				<% if can?(:update, FaqCategory) || can?(:delete, FaqCategory) %>
				<div class="sl_faq_category_menu">
					<% if can? :update, FaqCategory %>
					<%= link_to t(:link_edit), edit_faq_category_path(faq_category) %>
					<% end %>
					<% if can? :delete, FaqCategory %>
					<% if can? :update, FaqCategory %>
					<br />
					<% end %>					
					<%= link_to t(:link_delete), faq_category, method: :delete, data: { confirm: t(:delete_confirm) } %>
					<% end %>
				</div>
				<% end %>
				<% end %>
			</li>
			<% end %>
  		<% else %>
			<li><%=t(:no_data)%></li>
			<% end %>
		</ol>	
	<article>
		<% unless @faqs.empty? %>			
		<dl id="faqList">	
			<% @faqs.each do |faq| %>
			<dt <% if @faq %><% if @faq.id==faq.id %>class="on"<% end %><% end %>>
				<%= link_to truncate(faq.title,:length => 80), faqs_path(:faq_category_id=>params[:faq_category_id],:id=>faq),{:class=>'title'} %>
				<% if can?(:update, Faq) || can?(:delete, Faq) %>
				<div class="sl_faq_menu">
					<% if can? :update, Faq %>
					<%= link_to t(:link_edit), edit_faq_path(faq) %>
					<% end %>
					<% if can? :delete, Faq %>
					<% if can? :update, Faq %>
					&nbsp; | &nbsp;
					<% end %>
					<%= link_to t(:link_delete), faq, method: :delete, data: { confirm: t(:delete_confirm) } %>
					<% end %>
				</div>
				<% end %>
			</dt>
			<% if(@faq)%>
			<% if(faq.id==@faq.id) %>
					<dd><%=simple_format(@faq.faq_content.content) %></dd>
			<% end %>
			<% end %>
			
			<% end %>
			</dl>			
  			<% else %>	
  			<p><%=t(:no_data)%></p>
			<% end %>
	</article>
	<div id="sl_index_bottom_menu">
		<% if can? :create, FaqCategory %>
		<%= link_to 'FAQ 분류 생성',new_faq_category_path,:rel=>"nofollow" %>
		<% end %> 
		<% if can? :create, Faq %>
		<% if can? :create, FaqCategory %>		
				&nbsp; | &nbsp;
		<% end %>
		<%= link_to 'FAQ 생성',new_faq_path(:faq_category_id=>@categoryId),:rel=>"nofollow" %>		
		<% end %>
		<%= paginate @faqs %>
	</div>
</section>

app/views/faqs/new.html.erb
<section id="sl_faq_new">
	<%= render 'form' %>
	<%= link_to t(:link_list), faqs_path %>
</section>