config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :sessions => "users/sessions",:registrations => "users/registrations" }, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'} do
    get '/users', :to => 'users/registrations#index'
    get '/login', :to => 'users/sessions#new'
    get '/signup', :to => 'users/registrations#new'    
  end
  
  resources :installs,:intro,:histories,:contacts,:faq_categories, :faqs, :about, :gallery_categories, :galleries, :notices, :portfolios, :user_photos 
    
  resources :blogs do
    resources :blog_comments
  end
  
  resources :questions do
    get 'password',:on=>:collection
    post 'password',:on=>:collection    
    resources :question_comments
  end
  
  resources :guest_books do
    get 'password',:on=>:collection
    post 'password',:on=>:collection    
    resources :guest_book_comments do
      get 'password',:on=>:collection
      post 'password',:on=>:collection      
    end
  end
  
  get 'home/popup'=>'home#popup'
  
  get 'tags/:tag', to: 'blogs#index', as: :tag  
  
  get 'blogs/:blog_id/blog_comments/:id/password',:to=>'blog_comments#password'
  post 'blogs/:blog_id/blog_comments/:id/password',:to=>'blog_comments#password'
  
  
  get 'guest_books/:guest_book_id/:id/password',:to=>'guest_books#password'
  post 'guest_books/:guest_book_id/:id/password',:to=>'guest_books#password'    
  
  get 'guest_books/:guest_book_id/guest_book_comments/:id/password',:to=>'guest_book_comments#password'
  post 'guest_books/:guest_book_id/guest_book_comments/:id/password',:to=>'guest_book_comments#password'  
  
  # admin 
  get '/admin', :to=>'admin/home#index'
  
  namespace :admin do
    resources :resources,:users
    resources :intro,:gallery_categories, :galleries, :faq_categories,:faqs, :notices, :site, :intro, :contacts, :notices, :histories, :portfolios
    resources :questions do
      resources :question_comments
    end
    
    resources :blogs do
      resources :blog_comments
    end
    
    resources :questions do
      get 'password',:on=>:collection
      post 'password',:on=>:collection    
      resources :question_comments
    end
  
    resources :guest_books do
      resources :guest_book_comments do
        get 'password',:on=>:collection
        post 'password',:on=>:collection      
      end
    end    
  end
end

app/controllers/admin/intro_controller.rb
# encoding: utf-8

class Admin::IntroController < Admin::AdminController
  # GET /menus
  # GET /menus.json
  def index
    # @intro=Intro.page(params[:page]).per(15)
    @admin_users=User.where(:admin=>true)  
    
    @admin_user=User.where(:admin=>true,:intro=>true).first
    @admin_user_images=UserImage.where(:user_id=>@admin_user).page(params[:page]).order('id desc').per(15)
    
    if(params[:id])
      @admin_user_image = UserImage.find(params[:id])
    else
      @admin_user_image=@admin_user_images[0]
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_user }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @admin_intro = Intro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_user }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @admin_intro = Intro.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_intro }
    end
  end

  # GET /menus/1/edit
  def edit
    @admin_intro = Intro.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @admin_intro = Intro.new(params[:menu])

    respond_to do |format|
      if @admin_intro.save
        format.html { redirect_to @admin_intro, notice: '공지사항이 작성되었습니다.' }
        format.json { render json: @admin_intro, status: :created, location: @admin_intro }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_intro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @admin_intro = Intro.find(params[:id])

    respond_to do |format|
      if @admin_intro.update_attributes(params[:menu])
        format.html { redirect_to @admin_intro, notice: '공지사항이 수정되었습니다.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_intro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @admin_intro = Intro.find(params[:id])
    @admin_intro.destroy

    respond_to do |format|
      format.html { redirect_to admin_menus_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/intro_controller.rb
# encoding: utf-8

class IntroController < ApplicationController
  before_action :authenticate_user!, :except => [:index,:show] 

  def initialize(*params)
    super(*params)
        
    @controller_name=t('activerecord.models.intro')
    @script="intro"
    @title=t('activerecord.models.intro')+t(:title_separator)+t(:application_name)    
    @meta_description=t(:meta_description_intro)
    @page_itemtype="http://schema.org/ProfilePage"
  end
  
  # GET /intro
  # GET /intro.json  
  def index
    # @intro=Intro.page(params[:page]).per(15)
    @user=User.where(:admin=>true,:intro=>true).first
    @user_images=UserPhoto.where(:user_id=>@user).page(params[:page]).order('id desc').per(15)
    
    if(params[:id])
      @user_image = UserPhoto.find(params[:id])
    else
      @user_image=@user_images[0]
    end
    
    @script='intro'
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @user }
    end
  end
end

app/views/admin/intro/_form.html.erb
<%= form_for [:admin, @admin_notice],:html=>{:class=>'slboard_form'} do |f| %>
	<% if @admin_notice.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@admin_notice.errors.count, "error") %> prohibited this notice from being saved:</h2>
		<ul>
			<% @admin_notice.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title,{'class'=>'sl_input','required'=>'required'} %>
	</div>
	<%= f.fields_for :notice_content do |c| %>
	<div class="field">
		<%= c.label :content,'내용' %><br />
		<%= c.text_area :content,{'id'=>'sl_content','class'=>'sl_input','required'=>'required'}  %>
	</div>
	<% end %>
	<div class="actions">
		<%= f.submit '작성' %>
	</div>
<% end %>

app/views/admin/intro/edit.html.erb
<section id="admin_resource_edit">
  <%= render 'form' %>
  <%= link_to t(:link_show), admin_resource_path(@admin_resource) %> |
  <%= link_to t(:link_list), admin_resources_path %>
</section>

app/views/admin/intro/index.html.erb
<section id="admin_notice_index" class="table-responsive">
  <table width="100%" cellpadding="0" cellspacing="0" class="table table-striped table-hover">
		<colgroup>
			<col width="100px" />
			<col />
			<col width="70px" />
			<col width="130px" />
		</colgroup>
		<thead>
			<tr>
				<th><p class="sl_name">이름</p></th>
				<th><p class="sl_title">제목</p></th>
				<th class="sl_right"><p class="sl_count">조회</p></th>
				<th class="sl_right"><p class="sl_registered_date">등록일</p></th>
			</tr>
		</thead>
		<tbody>
			<tr class="none">
				<td><p class="sl_name"></p></td>
				<td><p><a class="sl_show_link" href="show.php"></a></p></td>
				<td class="sl_right"><p class="sl_count"></p></td>
				<td class="sl_right"><p class="sl_registered_date"></p></td>
			</tr>
			<% if @admin_users.empty? %>
			<% @admin_users.each do |admin_user| %>
			<tr>
				<td><p class="sl_name"><%= admin_user.name %></p></td>
				<td><p><%= link_to admin_user.title, intro  %></p></td>
				<td class="sl_right"><p class="sl_count"><%= admin_user.impressionist_count(:filter=>:ip_address) %></p></td>
				<td class="sl_right"><p class="sl_registered_date"><%=admin_user.created_at.to_date %></p></td>
			</tr>
			<% end %>			
			<% else %>
			<tr>
				<td colspan="4"><p>글이 없습니다.</p></td>
			</tr>
			<% end %>
</table>
		<div id="sl_bottom_menu">
	<% if user_signed_in? %>
	<% if current_user.admin? %>			
<%= link_to '글쓰기', new_admin_intro_path %>
	<% end %>
	<% end %>
</div>
</section>

app/views/admin/intro/new.html.erb
<section id="admin_resource_new">
  <%= render 'form' %>
  <%= link_to t(:link_list), admin_resources_path %>
</section>

app/views/admin/intro/show.html.erb
<section id="slboard_notice_show" class="slboard_main">
	<div class="section_top">
		<h2><%=@board_name %></h2>
		<p class="path"><%=link_to '홈으로',root_path,:title=>'홈으로' %>  &gt; <strong><%=@board_name %></strong></p>	
	</div>
	<p id="notice"><%= notice %></p>	
	<div class="slboard_content">
		<div class="sl_content_header">
			<h3><%= @admin_notice.title %></h3>
			<p>작성자 :<%= @admin_notice.user.name %>&nbsp;&nbsp;&nbsp; 작성일 : <%= @admin_notice.created_at %></p>
		</div>
		<div class="sl_content_main">
			<div class="sl_content_text">  <%= simple_format(@admin_notice.notice_content.content) %></div>
		</div>
	</div>
	<div id="sl_bottom_menu">
		<% if user_signed_in? %>
		<% if current_user.admin? %>
		<%= link_to '글쓰기', new_admin_notice_path %>
		<%= link_to '글수정', edit_admin_notice_path(@admin_notice) %>
		<% end %>
		<% end %>		
		<%= link_to '목록으로',admin_notices_path %>
	</div>
</section>